#!/usr/bin/python
import sys, os


def main(args):
    args = args[1:]
    if args:
        for arg in args:
            print os.path.abspath(arg)
    else:
        for line in sys.stdin:
            paths = line.split()
            for path in paths:
                print os.path.abspath(path)

if __name__ == '__main__':
    main(sys.argv)
