#!/usr/bin/python
import sys,os

args = sys.argv[1:]
if args:
   for arg in sys.argv[1:]:
        print os.path.abspath(arg)
else:
   for line in sys.stdin:
      paths = line.split()
      for path in paths:
         print os.path.abspath(path)

