#!/usr/local/bin/python

def main():
    printPythonPaths()

def printPythonPaths():
    import sys
    import studioenv
    print "\n".join(sys.path)

def printHandmadePaths():
    paths = []
    folioPaths = [
        '/rel/folio/pipeline/pipeline-5.5.20-latest',
        '/rel/folio/actionflow/actionflow-2.3.1-latest',
        '/rel/folio/handoff/handoff-1.3.1-latest',
        '/rel/folio/jose/jose-1.0-latest',
        ]
    otherPaths = [
        '/rel/lang/python/2.6.4-8/lib/python2.6/site-packages',
        '/rel/lang/python/2.6.4-8/lib/python2.6',
        '/rel/lang/python/2.6.4-8/lib/python2.6/plat-linux2',
        '/rel/lang/python/2.6.4-8/lib/python2.6/lib-tk',
        '/rel/lang/python/2.6.4-8/lib/python2.6/lib-old',
        '/rel/lang/python/2.6.4-8/opt-iccMaya2012_64/lib/python2.6/lib-dynload',
        '/rel/lang/python/2.6.4-8/lib/python2.6/site-packages',
        '/rel/lang/python/2.6.4-8/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info',
        '/rel/lang/python/2.6.4-8/opt-iccMaya2012_64/lib/python2.6/site-packages',
        '/rel/lang/python/2.6.4-8/opt-iccMaya2012_64/lib/python2.6/site-packages/Numeric',
        '/rel/lang/python/2.6.4-8/opt-iccMaya2012_64/lib/python2.6/site-packages/gst-0.10',
        '/rel/lang/python/2.6.4-8/opt-iccMaya2012_64/lib/python2.6/site-packages/gtk-2.0',
        ]
    paths += [p + "/python/lib/python2.7" for p in folioPaths]
    paths += [p + "/python/lib/python2.6" for p in folioPaths]
    paths += otherPaths
    print "\n".join(paths)

if __name__ == "__main__":
    main()
