#!/bin/tcsh

#dirs of the models you want to use
set DIRS = ""
foreach show ('mind mad3 kfp2 crood guardians pib')
    set $modelDir = "/studio/${show}/shdw_model/lib/model"
    cd $modelDir
    # gnome-terminal opens a new terminal window and executes the command
    # following the -c option
    gnome-terminal --execute tcsh -c '\
        pwd\
        set JOB = `pwd | awk -F/ '"'"'{print $3}'"'"'`\
        set SHDW = `pwd | awk -F/ '"'"'{print $4}'"'"' | awk -F_ '"'"'{print $2}'"'"'`\
        je $JOB-$SHDW -skip_cd_on_enter\
        
        
        echo Hit enter to close this terminal\
        set TERMINATE = $<\
'
   cd ../..
end




#!/bin/tcsh
set SHOWS = 'mind mad3 kfp2 crood guardians pib'
foreach SHOW ($SHOWS)
    tcsh -c "cd /studio/${SHOW}/mstr/general ; ani ; $* ; exit "
end
